fieldLayouts:
  03a3e1eb-f649-4101-9e8d-d569675d07fc:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 304a90dd-b08a-4ccf-9fe5-e20f6db20bd6
            warning: null
            width: 100
          -
            fieldUid: 69bde3b8-f6e5-4222-bab8-3ea6b61813f4 # Excerpt
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7b2feddb-199c-471f-b271-9676203022f1
            warning: null
            width: 100
          -
            fieldUid: 6b7d0378-db61-4649-b32e-a27ecb158986 # Feature Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6ecc6a36-0f3f-4335-b7a8-938b410fd37b
            warning: null
            width: 100
          -
            fieldUid: 4565f56d-6b28-4561-835c-e0d85a2bf0b8 # Post Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0c0ef57d-d639-49a2-a119-01cac91d8430
            warning: null
            width: 100
        name: Content
        uid: bf81c874-0b3b-45d2-be7d-efe03b992da5
handle: default
hasTitleField: true
name: Default
section: 7907913f-5c32-49b3-973d-c4fae76d77a9 # blog
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
