columnSuffix: null
contentColumnType: string
fieldGroup: b2e2ffa0-5642-476f-aec5-e8bcbcc6ea97 # Common
handle: postContent
instructions: 'The content of this post or page.'
name: 'Post Content'
searchable: false
settings:
  contentTable: '{{%matrixcontent_postcontent}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
