fieldLayouts:
  ec928d83-6f47-4da4-b4ed-2eae294c4565:
    tabs:
      -
        elements:
          -
            fieldUid: 0519a9c6-dd2a-4b8e-afca-97053358a8a7 # Footer Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b4bf4c22-b0e9-4e48-b0c8-ec47ca0ac36d
            warning: null
            width: 100
          -
            fieldUid: 02a7470e-3b8f-4fdd-8efc-4cc3d118bc3e # Logo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 26854bf4-cbbf-4d97-b365-5c5843a3d984
            warning: null
            width: 100
        name: 'Site Settings'
        uid: fe50ddab-4e7f-4877-85ed-18f0f893e92a
handle: siteSettings
name: 'Site Settings'
sortOrder: 1
