defaultPlacement: end
enableVersioning: true
handle: blog
name: blog
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  55d5b6d6-3047-4968-bb1d-d8b31ba06531: # craftcms_test.com
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: 'blog/{slug}'
type: channel
